version: "3"

# 1 service per container

services: 
  api:
    build: .
#    depends on: postgres
# at 13.59 use the above if you want to dockerize postgres along with fastapi code
    ports: 
      - 8000:8000
    # volumes:
    #   - ./:/usr/src/apps:ro
# use the above code to auto sync code changes to docker container.

#    env_file:
#      - ./.env

    environment:
      - database_hostname = postgres
      - database_port= 5432
      - database_name= fastapi
      - database_username= postgres
      - database_password= calgary
      - SECRET_KEY = 26h56g624kg654jgkjegwfvjkkebbcihxiochsDOP8999990077
      - ALGORITHM = HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES = 30

  # postgres:
  #   image: postgres
  #   environemnt:
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=fastapi

  #   volumes:
  #     - postgres-db:/var/lib/postgresql/data



